name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Start Server
        run: yarn dev &

      - name: Wait for Server to Start
        run: sleep 5

      - name: Run Jest Tests
        run: yarn jest
